import sys

file_path = "D:/harshithacontinue/b2b-main/b2b-main/backend/app/routes/partner_user.py"

with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

insert_idx = -1
for i, line in enumerate(lines):
    if "async def create_my_order(" in line:
        insert_idx = i
        break

if insert_idx == -1:
    print("Could not find create_my_order")
    sys.exit(1)

code_to_insert = """
class LoanDraftRequest(BaseModel):
    document_name: str
    language: str
    customer_name: str
    loan_amount: str
    tenure: str

@router.post("/loans/generate_draft")
def generate_loan_draft(
    req: LoanDraftRequest,
    current_partner_user: dict[str, Any] = Depends(get_current_partner_user),
):
    import io
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import letter
    from fastapi.responses import Response

    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, 750, f"{req.document_name.upper()} AGREEMENT")
    
    c.setFont("Helvetica", 12)
    c.drawString(100, 700, f"Language: {req.language}")
    c.drawString(100, 670, f"Customer Name: {req.customer_name}")
    c.drawString(100, 640, f"Loan Amount: Rs. {req.loan_amount}")
    c.drawString(100, 610, f"Tenure: {req.tenure} months")
    
    c.drawString(100, 560, "This is a professionally generated legal document draft.")
    c.drawString(100, 540, "Generated by LegalDesk B2B System.")
    
    c.showPage()
    c.save()
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return Response(content=pdf_bytes, media_type="application/pdf")

"""

lines.insert(insert_idx - 1, code_to_insert) # Insert before @router.post("/orders")

with open(file_path, "w", encoding="utf-8") as f:
    f.writelines(lines)

print("Injected generate_loan_draft into partner_user.py")
