// Constants sourced from SignDesk's "DSS 2.0 API" document (eStamp / Stamp
// Request API) — Annexure 1 (document categories), Annexure 2.1 (states
// where the service is available), and the request-parameter descriptions
// for first_party_entity_type / first_party_id_type (and their second-party
// equivalents).

// Annexure 2.1: States and State Codes where service is available.
export const STAMP_STATES = [
  ["AP", "Andhra Pradesh"],
  ["DL", "Delhi"],
  ["HR", "Haryana"],
  ["KA", "Karnataka"],
  ["KL", "Kerala"],
  ["MH", "Maharashtra"],
  ["TN", "Tamil Nadu"],
  ["TS", "Telangana"],
  ["UP", "Uttar Pradesh"],
  ["WB", "West Bengal"],
  ["GJ", "Gujarat"],
  ["MP", "Madhya Pradesh"],
  ["AS", "Assam"],
  ["BR", "Bihar"],
  ["CG", "Chhattisgarh"],
  ["GA", "Goa"],
  ["HP", "Himachal Pradesh"],
  ["JK", "Jammu and Kashmir"],
  ["OD", "Orissa"],
  ["PB", "Punjab"],
  ["RJ", "Rajasthan"],
  ["UK", "Uttarakhand"],
].map(([value, label]) => ({ value, label }));

export const PARTY_ENTITY_TYPES = ["Individual", "Organization", "Government", "Foreign"];

// Which first/second_party_id_type values are valid for a given entity type.
export const ID_TYPES_BY_ENTITY = {
  Individual: [
    { value: "DLN", label: "Driving Licence (DLN)" },
    { value: "PAN", label: "PAN" },
    { value: "PPN", label: "Passport (PPN)" },
    { value: "VID", label: "Voter ID (VID)" },
    { value: "UID", label: "Aadhaar (UID)" },
  ],
  Organization: [{ value: "PAN", label: "PAN" }],
  Government: [{ value: "TAN", label: "TAN" }],
  Foreign: [{ value: "FID", label: "Foreign ID (FID)" }],
};

// Annexure 1: Document categories (name, code) — full 415-entry list.
// NOTE: the source document itself skips code 323 and reuses code 324 for
// two different names ("LETTER OF INDEMNITY - B KHATA PROPERTY" and
// "DECLARATION CUM UNDERTAKING BY BORROWER(S)") — preserved as-is since
// these codes are sent verbatim to SignDesk's API.
const RAW_DOCUMENT_CATEGORIES = [
  [1, "Service/General Agreement"],
  [2, "Agreement relating to Deposit of Title Deeds"],
  [3, "Mortgage Deed"],
  [4, "Agreement Relating to Pawn or Pledge"],
  [5, "Security Bond Mortgage Deed"],
  [6, "Loan Agreement"],
  [7, "Leave and License Agreement"],
  [8, "Affidavit"],
  [9, "Deed of Hypothecation"],
  [10, "Guarantee"],
  [11, "Power of Attorney authorising person/s for one transaction"],
  [12, "Power of Attorney authorizing to sell immovable property"],
  [13, "Loan Agreement Unsecured"],
  [14, "Car Loan/Loan Agreement"],
  [15, "Incentive Payout Management Agreement"],
  [16, "Indemnity Bond"],
  [17, "Vehicle Lease Agreement"],
  [18, "Deed of further charge"],
  [19, "Indenture of Mortgage"],
  [20, "Agreement relating to Sale of Immovable property"],
  [21, "Master Facility Agreement/Supplementary Agreement"],
  [22, "ESCROW"],
  [23, "Declaration"],
  [24, "Undertaking"],
  [25, "Counterpart or Duplicate"],
  [26, "Agreement - Media Advertisement"],
  [27, "Customs Bond or Excise Bond"],
  [28, "Power of Attorney"],
  [29, "Hire purchase"],
  [30, "Bond"],
  [31, "House lease agreement"],
  [32, "Letter of appropriation"],
  [33, "Letter of continuity"],
  [34, "Partnership"],
  [35, "Non Disclosure Agreement"],
  [36, "Release"],
  [37, "Assignment of Debt"],
  [38, "Conveyance"],
  [39, "Mortgage Collateral"],
  [40, "Debenture"],
  [41, "Power of Attorney - GPA"],
  [42, "Power of Attorney - Authenticated GPA"],
  [43, "Promissory Note"],
  [44, "Deed of Confirmation"],
  [45, "Article of Association of a company"],
  [46, "Letter of Allotment of Shares"],
  [47, "Memorandum of Association"],
  [48, "Share Certificates"],
  [49, "Work Contract"],
  [50, "Advt & Promo Service Agreement"],
  [51, "Annexure A to SL CC-OD"],
  [52, "Individual Facility Agreements/MFA"],
  [53, "Letter of Appropriation, Set Off & Lien (FX)"],
  [54, "Acknowledgment of Debt"],
  [55, "Letter of Appropriation, Set Off & Lien"],
  [56, "Others"],
  [57, "Term Loan Agreement"],
  [58, "Cash Credit Agreement"],
  [59, "Packing Credit Agreement"],
  [60, "Overdraft Agreement"],
  [61, "Short Term Loan Agreement"],
  [62, "Master Letter of Credit Agreement"],
  [63, "Bill Discounting Agreement"],
  [64, "Buyers Credit Agreement"],
  [65, "Transposition Agreement"],
  [66, "Supplemental MFA"],
  [67, "Supplemental Facility Agreement"],
  [68, "ISDA Agreement"],
  [69, "Forward Contract Declaration"],
  [70, "BG Indemnity"],
  [71, "LC Indemnity"],
  [72, "SBLC Indemnity"],
  [73, "Foreign Currency Indemnity"],
  [74, "General Counter Guarantee cum Indemnity"],
  [75, "General Indemnity CUM Undertaking-Documentary Credit"],
  [76, "Supplemental DOH"],
  [77, "Corporate Guarantee"],
  [78, "Personal Guarantee"],
  [79, "Confirmation from Guarantor"],
  [80, "Pledge Agreement"],
  [81, "Employee Agreement"],
  [82, "Remedial Restructuring Secured Loan"],
  [83, "B2C Restructuring Unsecured Loan"],
  [84, "Application Form"],
  [85, "T&C cum Indemnity"],
  [86, "Authority Letter"],
  [87, "Lease Agreement"],
  [88, "Software Agreement"],
  [89, "Framework Agreement"],
  [90, "Further charge -if org mortgage is with possession"],
  [91, "Further charge-if with possession"],
  [92, "Further charge-if without possession"],
  [93, "Mortgage deed-with possession"],
  [94, "Mortgage deed-without possession"],
  [95, "Mortgage deed-collateral"],
  [96, "POA for admitting execution of deed in registration"],
  [97, "POA authorizing a person for more transaction"],
  [98, "POA authorizing person's for one transaction"],
  [99, "MHA - 10 - Article of Association of a Company"],
  [100, "MHA - 13 - Bond"],
  [101, "MHA - 15 - Cancellation (not of Conveyance)"],
  [102, "MHA - 16 - Certificate of Sale"],
  [103, "MHA - 17 - Share Certificate"],
  [104, "MHA - 24-Composition Deed"],
  [105, "MHA - 25 (a) - Conveyance of movable property"],
  [106, "MHA - 27 - Counterpart or Duplicate"],
  [107, "MHA - 29- Delivery order in respect of goods"],
  [108, "MHA - 3- Adoption Deed"],
  [109, "MHA - 32- Exchange of Property"],
  [110, "MHA - 33 (a)-Further Charge (if org mortgage is with possession)"],
  [111, "MHA - 33 (b) (1)-Further Charge (if with possession)"],
  [112, "MHA - 33 (b) (2)-Further Charge (if without possession)"],
  [113, "MHA - 34- Gift Deed"],
  [114, "MHA - 35- Indemnity Bond"],
  [115, "MHA - 36- lease for term exceeding one year"],
  [116, "MHA - 36A-leave and Licence Agreement"],
  [117, "MHA - 37 - letter of allotment of Shares"],
  [118, "MHA - 39 - Memorandum of Association of Company"],
  [119, "MHA - 4- Affidavit"],
  [120, "MHA - 40 (a)- mortgage deed (with possession)"],
  [121, "MHA - 40 (b)- mortgage deed (without possession)"],
  [122, "MHA - 40 ( c)- mortgage deed (collateral)"],
  [123, "MHA - 46- Partition"],
  [124, "MHA - 47 (1) (a)- Partnership if share contri. is not immovable prop"],
  [125, "MHA - 47 (1) (b)- Partnership if share contri. is immovable prop"],
  [126, "MHA - 47 (2) (a)- Dissolution of Partnership if share is immovable"],
  [127, "MHA - 47 (2) (b)- Dissolution of Partnership in other cases"],
  [128, "MHA - 48 (a)- POA for admitting execution for deed in registration"],
  [129, "MHA - 48 (b)- POA for court purpose"],
  [130, "MHA - 48 (c)- POA authorising person/s for one transaction"],
  [131, "MHA - 48 (d)- POA authorising a person for more transaction"],
  [132, "MHA - 48 (e)- POA authorising person for transaction/s"],
  [133, "MHA - 48 (f)- Power of Attorney authorising to sell Immovable property"],
  [134, "MHA - 48 (f)(1)- POA with consideration and authorising to sell prop"],
  [135, "MHA - 48 (f)(2)(a)- POA without consid to family member to sell prop"],
  [136, "MHA - 48 (f)(2)(b)- POA without consid to non family member to sell prop"],
  [137, "MHA - 48 (g)- POA authorising to develop"],
  [138, "MHA - 5 (g-a) (2)- Development Agreement"],
  [139, "MHA - 5 (g-d) - Agreement to transfer of tenancy rights"],
  [140, "MHA - 5 (g-e) - Agreement hire purchase"],
  [141, "MHA - 5 (h) (A) (1) - Agreement relating to advertisement on mass media"],
  [142, "MHA - 5 (h) (A) (2) - Agreement relating to right of telecasting etc"],
  [143, "MHA - 5 (h) (A) (3) - Agreement relating to specific performance"],
  [144, "MHA - 5 (h) (A) (4) - Agreement creating right and having monetary value"],
  [145, "MHA - 5 (h) (A) (5) - Agreement relating to Assignment of copyright"],
  [146, "MHA - 5 (h) (A) (6) - Agreement relating to BOT project"],
  [147, "MHA - 5 (h) (b) (6) - Agreement- if not otherwise provided for"],
  [148, "MHA - 51- Reconveyance of mortgaged property"],
  [149, "MHA - 52 (a)- Release of ancestral property"],
  [150, "MHA - 52 (b)- Release not of ancestral property"],
  [151, "MHA - 54- Security bond"],
  [152, "MHA - 55 (A) (1)- Settlement for religious/charitable purpose"],
  [153, "MHA - 58 (a)- Surrender of Lease,Without consideration"],
  [154, "MHA - 58 (b)- Surrender of Lease,With consideration"],
  [155, "MHA - 6 (1). 1-Agreement to deposit of title deed"],
  [156, "MHA - 6 (1). 2- Equitable Mortgage"],
  [157, "MHA - 6 (2) -hypothecation,pawn,pledge"],
  [158, "MHA - 60- Transfer of Lease"],
  [159, "MHA - 63- Work Contract"],
  [160, "MHA - 25 b- Agreement to sell/Transfer/Assignment"],
  [161, "MHA - 25 c-Deed of Apartment"],
  [162, "MHA - 25 d-Cancellation of Sale deed"],
  [163, "Addendum"],
  [164, "Amendment agreement"],
  [165, "Change request – CR /RFC/CRF"],
  [166, "Enterprise agreement"],
  [167, "Letter of Engagement"],
  [168, "Letter of Intent"],
  [169, "Maintenance agreement"],
  [170, "Master Service Agreement"],
  [171, "MOU"],
  [172, "Order form"],
  [173, "Purchase Order"],
  [174, "Reference Letter"],
  [175, "Sales Order"],
  [176, "Software License Agreement"],
  [177, "SOW"],
  [178, "Cancellation of Instruments"],
  [179, "Settlement"],
  [180, "Share Warrants"],
  [181, "Rectification Deed- Immovable"],
  [182, "Sale"],
  [183, "Sale Agreement"],
  [184, "Further Charge"],
  [185, "Perpetual"],
  [186, "Lease- Rent deed upto 1 year"],
  [187, "Lease upto 5 years"],
  [188, "Lease upto 10 years"],
  [189, "Lease upto 20 years"],
  [190, "Lease upto 30 years"],
  [191, "Lease upto 100 years"],
  [192, "Lease upto 200 years"],
  [193, "Lease with security upto 5 years"],
  [194, "Lease with security upto 10 years"],
  [195, "Lease with security upto 20 years"],
  [196, "Lease with security upto 30 years"],
  [197, "Lease with security upto 100 years"],
  [198, "Lease with security upto 200 years"],
  [199, "Record of Transaction (Electronics or Otherwise) effected by a trading member (Broker Note)"],
  [200, "Memorandum of Settlement"],
  [201, "Consent Letter"],
  [202, "Rectification Deed- Movable"],
  [203, "Bill of Exchange"],
  [204, "Policy of Insurance"],
  [205, "Power of attorney –SPA"],
  [206, "Disclaimer"],
  [207, "Revocation of Trust"],
  [208, "Dissolution Deed"],
  [209, "Deed of Retirement"],
  [210, "L.C. (Letter Certificate)"],
  [211, "Trust"],
  [212, "Appointment in Execution of a Power"],
  [213, "Appraisement or Valuation"],
  [214, "Bill of Exchange"],
  [215, "Bill of Lading"],
  [216, "Composition Deed"],
  [217, "Copy or extract"],
  [218, "Release of Right In favour of Co-owner"],
  [219, "Release of right in favour of Partner"],
  [220, "Revocation of -of, or concerning, any property when made by any instrument other than a Will"],
  [221, "Warrant of Goods"],
  [222, "Agreement relating to Sale of Immovable property"],
  [223, "Appointment in execution of a power"],
  [224, "Appraisement or Valuation"],
  [225, "Article of Association"],
  [226, "Certificate or other documents, evidencing the right or title of the holder there of, or any other person, either to any share, script or stock in or of any incorporated company or other body corporate or to become proprietor of share, script or stock in of any such company or body"],
  [227, "Certificate of Enrolment as Advocate"],
  [228, "Clearance List"],
  [229, "Home Loan Agreement"],
  [230, "Loan Against Property Agreement"],
  [231, "Business Installment Loan Agreement"],
  [232, "Affidavit for dual signature"],
  [233, "Borrowers Indemnity (Balance Transfer)"],
  [234, "HUF Declaration"],
  [235, "Affidavit for Dual DOB"],
  [236, "Affidavit for Dual Name"],
  [237, "Declaration-cum-Undertaking-Ready to Occupy Properties"],
  [238, "Factoring Agreement"],
  [239, "Debt Subordination Agreement"],
  [240, "Undertaking cum Indemnity (Fax Indemnity)"],
  [241, "Indemnity for Bill Discounting Limit"],
  [242, "Non Disposable Undertaking"],
  [243, "Customer Undertaking"],
  [244, "Partnership Authority Letter"],
  [245, "End Use Undertaking"],
  [246, "Letter of General Lien and Set off"],
  [247, "Memorandum of Deposit of Title Deeds"],
  [248, "Undertaking to Create Mortgage"],
  [249, "PoA BT"],
  [250, "Deed of Guarantee"],
  [251, "DPN"],
  [252, "Sole Proprietors Letter"],
  [253, "Undertaking cum Indemnity"],
  [254, "Letter of General line and set off"],
  [255, "Undertaking about lamination from Borrower"],
  [256, "Letter of continuity guarantee"],
  [257, "Indemnity for Loss of RR receipt/Boundaries differ"],
  [258, "Memorandum of deposit of title deeds for creation of mortgage (EM)"],
  [259, "Deed of Mortgage (RM)"],
  [260, "Dual Name, DOB and Signature Affidavit"],
  [261, "Commercial Vehicle Loan Agreement"],
  [262, "Letter of continuity for Demand Promissory Note"],
  [263, "AGREEMENT WITH BUSINESS PARTNERS (DSA)"],
  [264, "SERVICE PROVIDER AGREEMENT (Vendor)"],
  [265, "Vernacular"],
  [266, "Other Stamp duty (If any)"],
  [267, "UNDERTAKING to Create Mortgage"],
  [268, "Acknowledgment"],
  [269, "Agreement"],
  [270, "Cancellation of Instruments"],
  [271, "F&B Agreement"],
  [272, "Indemnity"],
  [273, "Lease of immovable property - Commercial"],
  [274, "Lease of immovable property - Residential"],
  [275, "Lease of Movable property"],
  [276, "License of Immovable and Movable Property"],
  [277, "Maintenance Contract"],
  [278, "Novation Agreement"],
  [279, "Retail Agreement"],
  [280, "Service Provider Right Holder Agreement"],
  [281, "Supply Agreement"],
  [282, "Confidentiality Agreement"],
  [283, "Supply and Service Agreement"],
  [284, "Utility Service Agreement"],
  [285, "Fixed Period Rental & Maintenance Agreement"],
  [286, "Consultancy Agreement /Consultancy Service Agreement"],
  [287, "Limited Liability Partnership"],
  [288, "LAS Application Form"],
  [289, "LAS Agreement"],
  [290, "LAS Sanction letter"],
  [291, "Loan Cum Hypothecation"],
  [292, "Irrevocable Power of Attorney"],
  [293, "Declaration cum confirmation Deed"],
  [294, "Affidavit Cum Undertaking"],
  [295, "Guarantee Bond"],
  [296, "Partnership: (with immoveable property)"],
  [297, "Transfer of Lease"],
  [298, "Delivery order-goods"],
  [299, "Article of Association of Company"],
  [300, "Agreement to hire purchase"],
  [301, "Lease of Immovable Property"],
  [302, "Transfer of License"],
  [303, "Lease - (Imm. Property) - Premium or Money Adv."],
  [304, "Dealer and RC Limit Agreement"],
  [305, "Commercial Letters of Credit"],
  [306, "DDPI for Under (5 (i)(i-a))"],
  [307, "Cooperation agreement"],
  [308, "Arbitration Award"],
  [309, "DDPI POA"],
  [310, "Reconveyance of Mortgage"],
  [311, "Surrender of Lease"],
  [312, "Agreement relating to Sales of Immovable Property"],
  [313, "Letter of Allotment"],
  [314, "Letter of License"],
  [315, "Memorandum of Association of a company"],
  [316, "Exchange of Property"],
  [317, "Service Contract"],
  [318, "Grant Agreement"],
  [319, "Logistics Agreement"],
  [320, "Power Purchase Agreement"],
  [321, "DECLARATION AND ACKNOWLEDGEMENT"],
  [322, "AFFIDAVIT CUM BUILDING PLAN"],
  [324, "LETTER OF INDEMNITY - B KHATA PROPERTY"],
  [324, "DECLARATION CUM UNDERTAKING BY BORROWER(S)"],
  [325, "UNDERTAKING-CUM-INDEMNITY - TITLE DEED DAMAGED DOCUMENTS"],
  [326, "UNDERTAKING-CUM-INDEMNITY -TITLE DEED LAMINATED DOCUMENTS"],
  [327, "DECLARATION FOR SIGNING IN VERNACULAR LANGUAGE"],
  [328, "DECLARATION FOR CROSS LINKING"],
  [329, "DECLARATION FOR PLOT"],
  [330, "INDEMNITY FOR PROPERTY SCHEDULE MISMATCH"],
  [331, "Gold Loan"],
  [332, "Lease Deed"],
  [333, "Regularised Undertaking"],
  [334, "Thumb Impression"],
  [335, "Lost of documents undertaking"],
  [336, "DECLARATION & ACK FOR ROC charges creation"],
  [337, "Guarantor deed"],
  [338, "MOE Stamp paper-338"],
  [339, "MOTD"],
  [340, "Locker Agreement"],
  [341, "Memorandum of Entry"],
  [342, "Declaration Cum Undertaking"],
  [343, "ECLGS - TL Agreement"],
  [344, "Security Letter"],
  [345, "MHA - 34- Gift Deed-Movable"],
  [346, "MHA - 34- Gift Deed-Immovable"],
  [347, "MHA - 27 - Counterpart or Duplicate-Movable"],
  [348, "MHA - 27 - Counterpart or Duplicate-Immovable"],
  [349, "MHA - 27 - Counterpart or Duplicate-NA"],
  [350, "MHA - 54- Security bond-Movable"],
  [351, "MHA - 54- Security bond-Immovable"],
  [352, "MHA - 54- Security bond-NA"],
  [353, "MHA - 63- Work Contract-Movable"],
  [354, "MHA - 63- Work Contract-Immovable"],
  [355, "MHA - 63- Work Contract-NA"],
  [356, "SUB-BC AGREEMENT"],
  [357, "Apprenticeship Deed"],
  [358, "Loan Agreement/Hypothecation Deed/Indemnity/Declaration"],
  [359, "Limited Liability Partnership - Capital more than 10 lakhs"],
  [360, "Lease of Immovable Property - Not exceeding 1 year in case of Residential property"],
  [361, "Lease of Immovable Property - Not exceeding 1 year in case of commercial industrial property"],
  [362, "Deed of Hypothecation for Loan upto Rs.10 lakhs"],
  [363, "Deed of Hypothecation for Loan exceeding Rs.10 lakhs"],
  [364, "Deed of Hypothecation credit facility upto 10 lakhs"],
  [365, "Deed of Hypothecation-2"],
  [366, "Indenture of Mortgage-2"],
  [367, "Undertaking for LLP Partners-2"],
  [368, "ECLGS Guarantee Deed-2"],
  [369, "ECLGS Deed of Hypothecation-3"],
  [370, "ECLGS Deed of Hypothecation-4"],
  [371, "Pledge Agreement-2"],
  [372, "Memorandum of Entry-2"],
  [373, "Power of Attorney - In favor of upto 10 persons INR 1000"],
  [374, "Car Loan/Loan Agreement greater than 10L"],
  [375, "Agreement relating to Deposit of Title Deeds - Loan above 10 lacs"],
  [376, "Agreement-transfer of intellectual property rights, patent rights, trade market rights, copyrights"],
  [377, "Power of Attorney - for admitting executing of document"],
  [378, "Power of Attorney - for authorising one or more person to act in a single transaction"],
  [379, "Power of Attorney - for authorising more than 5 person to act jointly"],
  [380, "Power of Attorney - authorizing more than 5 to 10 persons to act jointly in more than one transaction or generally"],
  [381, "Power of Attorney - Authorizing to sell property"],
  [382, "Power of Attorney - when sale power given to other than family members"],
  [383, "Power of Attorney - when given for trading operation"],
  [384, "Power of Attorney - when given for depository participant"],
  [385, "Power of Attorney - in any other case"],
  [386, "Letter of License - Not more than 1 year in case of commercial industrial property"],
  [387, "Letter of License - 1 year to 10 year"],
  [388, "Letter of License - 10 year to 20 year"],
  [389, "Letter of License - 20 to 30 year"],
  [390, "Letter of License - Not more than 1 year in case of residential property"],
  [391, "Agreement Relating to Pawn or Pledge greater than 10L"],
  [392, "Memorandum of deposit of title deeds for creation of mortgage - less than 10L"],
  [393, "Agreement Relating to Pawn or Pledge above 10 lakh"],
  [394, "Acknowledgment of Debt 2"],
  [395, "Bond - Amount secured does not exceed 1000"],
  [396, "Bond - Amount exceeding 1000"],
  [397, "End User License Agreement"],
  [398, "Outsourcing Agreement"],
  [399, "Interest Subvention Agreement"],
  [400, "Agreement Of Guarantee"],
  [401, "Unattested Deed Of Hypothecation"],
  [402, "Colending Framework And Servicing Agreement"],
  [403, "Agreement For Appointment Of Service Partner"],
  [404, "Article - 5 General Agreement"],
  [405, "Article Others"],
  [406, "Article 48(C) Power Of Attorney"],
  [407, "Article 6(2) Pledge, Loan Or Hypothecation-Movable"],
  [408, "Article 5(H) Agreement (Not Otherwise provided For)"],
  [409, "Article 45(C) Power Of Attorney-Other Than Article 45(A)"],
  [410, "DDPI for NSDL"],
  [411, "Distribution & License Agreement"],
  [412, "Renewal of Distribution and License Agreement"],
  [413, "Production Agreement"],
  [414, "Agreement to Sell Intellectual Property"],
  [415, "Memorandum of entry by deposit of title deed"],
];

// value stays the raw numeric code (what's actually sent to SignDesk);
// _key is only for React's list `key` prop, since code 324 appears twice in
// the source document (see the note above) and array indices alone would be
// fragile if this list is ever reordered.
export const DOCUMENT_CATEGORIES = RAW_DOCUMENT_CATEGORIES.map(([value, label], index) => ({
  value,
  label: `${value} – ${label}`,
  _key: `${value}-${index}`,
}));
